# Generated by Django 4.1.2 on 2022-10-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParadigma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
